sudo: required
services:
  - docker

before_install:
  - docker build -t raju-kaju/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run raju-kaju/react-test npm test -- --coverage

after_success:
  - docker build -t rajukaju/multi-client ./client
  - docker build -t rajukaju/multi-nginx ./nginx
  - docker build -t rajukaju/multi-server ./server
  - docker build -t rajukaju/multi-worker ./worker
  #log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images and push them to docker hub
  - docker push rajukaju/multi-client
  - docker push rajukaju/multi-nginx
  - docker push rajukaju/multi-server
  - docker push rajukaju/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-171800269131"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
